# Generated by Django 5.1 on 2024-08-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "overall_rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="Overall rating"
                    ),
                ),
                (
                    "total_number_of_ratings",
                    models.CharField(
                        max_length=6, verbose_name="Total number of ratings"
                    ),
                ),
                (
                    "uid",
                    models.CharField(max_length=22, unique=True, verbose_name="UID"),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Added at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Podcast",
                "verbose_name_plural": "Podcasts",
                "ordering": ["-added_at"],
            },
        ),
    ]
